spring.application.name=musicplayer

spring.mongodb.uri=mongodb://localhost:27017/MusicPlayer

jwt.secret=${JWT_SECRET}

logging.level.org.springframework.security=DEBUG

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


 

